In [104]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time
import re
import pandas as pd

In [108]:
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get("https://startuplist.africa/industries")
time.sleep(5)


items = driver.find_elements(By.CSS_SELECTOR, "a[href^='/industry/']")

data = []
pattern = re.compile(r"\((\d+)\)")


for item in items:
    parent = item.find_element(By.XPATH, '..')
    full_text = parent.text.strip()
    link = item.get_attribute('href')



    match = pattern.search(full_text)
    count = int(match.group(1)) if match else None

    data.append({
        "name": full_text, 
        "count": count,
        "link": link
    })

driver.quit()

df = pd.DataFrame(data)
print(df)

df.to_csv("startup_industries.csv", index=False)

                              name  count  \
0                     3D Games (1)    1.0
1                3D Technology (8)    8.0
2                  3D printing (1)    1.0
3                   Ad Network (1)    1.0
4                       AdTech (6)    6.0
...                            ...    ...
1455                   Health care    NaN
1456                   Marketplace    NaN
1457                    E-Commerce    NaN
1458       Artificial Intelligence    NaN
1459  Software-as-a-service (SaaS)    NaN

                                                   link
0          https://startuplist.africa/industry/3d-games
1     https://startuplist.africa/industry/3d-technology
2       https://startuplist.africa/industry/3d-printing
3        https://startuplist.africa/industry/ad-network
4            https://startuplist.africa/industry/adtech
...                                                 ...
1455    https://startuplist.africa/industry/health-care
1456    https://startuplist.africa/industry/marketplace
1457     https://startuplist.africa/industry/e-commerce
1458  https://startuplist.africa/industry/artificial...
1459           https://startuplist.africa/industry/saas

[1460 rows x 3 columns]

In [110]:
df = pd.read_csv('startup_industries.csv')
df

,name,count,link
0,3D Games (1),1.0,https://startuplist.africa/industry/3d-games
1,3D Technology (8),8.0,https://startuplist.africa/industry/3d-technology
2,3D printing (1),1.0,https://startuplist.africa/industry/3d-printing
3,Ad Network (1),1.0,https://startuplist.africa/industry/ad-network
4,AdTech (6),6.0,https://startuplist.africa/industry/adtech
...,...,...,...
1455,Health care,NaN,https://startuplist.africa/industry/health-care
1456,Marketplace,NaN,https://startuplist.africa/industry/marketplace
1457,E-Commerce,NaN,https://startuplist.africa/industry/e-commerce
1458,Artificial Intelligence,NaN,https://startuplist.africa/industry/artificial...
1459,Software-as-a-service (SaaS),NaN,https://startuplist.africa/industry/saas

In [112]:
df['name'] = df['name'].str.replace(r'\s*\(\d+\)', '', regex=True)

df['count'] = df['count'].fillna(0).astype(int)

In [114]:
df

,name,count,link
0,3D Games,1,https://startuplist.africa/industry/3d-games
1,3D Technology,8,https://startuplist.africa/industry/3d-technology
2,3D printing,1,https://startuplist.africa/industry/3d-printing
3,Ad Network,1,https://startuplist.africa/industry/ad-network
4,AdTech,6,https://startuplist.africa/industry/adtech
...,...,...,...
1455,Health care,0,https://startuplist.africa/industry/health-care
1456,Marketplace,0,https://startuplist.africa/industry/marketplace
1457,E-Commerce,0,https://startuplist.africa/industry/e-commerce
1458,Artificial Intelligence,0,https://startuplist.africa/industry/artificial...
1459,Software-as-a-service (SaaS),0,https://startuplist.africa/industry/saas

In [120]:
df.rename(columns ={'name' : 'industry'}, inplace=True)

In [122]:
df

,industry,count,link
0,3D Games,1,https://startuplist.africa/industry/3d-games
1,3D Technology,8,https://startuplist.africa/industry/3d-technology
2,3D printing,1,https://startuplist.africa/industry/3d-printing
3,Ad Network,1,https://startuplist.africa/industry/ad-network
4,AdTech,6,https://startuplist.africa/industry/adtech
...,...,...,...
1455,Health care,0,https://startuplist.africa/industry/health-care
1456,Marketplace,0,https://startuplist.africa/industry/marketplace
1457,E-Commerce,0,https://startuplist.africa/industry/e-commerce
1458,Artificial Intelligence,0,https://startuplist.africa/industry/artificial...
1459,Software-as-a-service (SaaS),0,https://startuplist.africa/industry/saas

In [124]:
df.to_csv("startup_industries.csv", index=False)

In [128]:
df.head(100)

           industry  count                                               link
0          3D Games      1       https://startuplist.africa/industry/3d-games
1     3D Technology      8  https://startuplist.africa/industry/3d-technology
2       3D printing      1    https://startuplist.africa/industry/3d-printing
3        Ad Network      1     https://startuplist.africa/industry/ad-network
4            AdTech      6         https://startuplist.africa/industry/adtech
..              ...    ...                                                ...
95           Bakery      2         https://startuplist.africa/industry/bakery
96        Bloggging      0      https://startuplist.africa/industry/bloggging
97        Biopharma      1      https://startuplist.africa/industry/biopharma
98          Boating      1        https://startuplist.africa/industry/boating
99  Book publishing      1  https://startuplist.africa/industry/book-publi...

[100 rows x 3 columns]